[package]
name = "py-arrow-bigquery"
version = "0.1.0"
edition = "2021"

[lib]
name = "arrow_bigquery"
crate-type= ["cdylib"]

[dependencies]
chrono = "0.4"
google-cloud-auth = "1.17.0"
google-cloud-bigquery = "0.18.0"
http = "1.0"
arrow-bigquery-lib = { package = "arrow-bigquery", path = "../crates/arrow-bigquery" }
pyo3 = { version = "0.27", features = ["abi3-py310", "chrono"] }
pyo3-async-runtimes = { version = "0.27", features = ["attributes", "tokio-runtime"] }
pyo3-polars = { version = "0.26.0", features = ["derive", "lazy"] }
polars-arrow = { version = "0.53.0", default-features = false }
tokio = { version = "1.51.0", features = ["rt", "sync", "time"] }
tracing = "0.1"

[features]
extension-module = ["pyo3/extension-module"]
testing = ["arrow-bigquery-lib/testing"]
default = ["testing"]

[dev-dependencies]
google-cloud-gax = "1.15.0"
