[package]
name = "arrow-bigquery"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.0"
chrono = "0.4"
google-cloud-auth = { git = "https://github.com/tswast/google-cloud-rust.git", branch = "tswast-bq-storage-reader" }
google-cloud-bigquery = { git = "https://github.com/tswast/google-cloud-rust.git", branch = "tswast-bq-storage-reader" }
google-cloud-gax = { git = "https://github.com/tswast/google-cloud-rust.git", branch = "tswast-bq-storage-reader" }
google-cloud-wkt = { git = "https://github.com/tswast/google-cloud-rust.git", branch = "tswast-bq-storage-reader" }
polars-arrow = { version = "0.53.0", default-features = false, features = ["io_ipc", "io_ipc_compression"] }
polars-error = "0.53.0"
rustls = { version = "0.23.37", features = ["aws_lc_rs"] }
tokio = "1.51.0"
tracing = "0.1"
tracing-subscriber = { version ="0.3", features = ["env-filter"] }
winnow = "1.0.4"

[lib]
bench = false

[dev-dependencies]
tokio = { version = "1.51.0", features = ["rt-multi-thread", "macros"] }
criterion = { version = "0.5.1", features = ["async_tokio", "html_reports"] }

[[bench]]
name = "read"
harness = false
