name: Test Python (Integration)

on:
  pull_request:
    paths:
      - Cargo.lock
      - crates/**
      - docs/source/src/python/**
      - py-polars-bigquery/**
      - .github/workflows/test-python-integration.yml
  push:
    branches:
      - main
    paths:
      - Cargo.lock
      - crates/**
      - docs/source/src/python/**
      - py-polars-bigquery/**
      - .github/workflows/test-python-integration.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -C debuginfo=0 # Do not produce debug symbols to keep memory usage down
  RUST_BACKTRACE: 1
  PYTHONUTF8: 1

defaults:
  run:
    working-directory: py-polars-bigquery
    shell: bash

jobs:
  test-python-integration:
    name: Test Python (Integration)
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write # Google Cloud auth
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.14']

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: Free some disk space (remove unused packages)
        uses: endersonmenezes/free-disk-space@7901478139cff6e9d44df5972fd8ab8fcade4db1 #v3.2.2
        if: ${{ matrix.os != 'windows-latest' }}
      - uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' #v3.0.0
        with:
          service_account: 'github-actions-sa@polars-bigquery.iam.gserviceaccount.com'
          workload_identity_provider: projects/700739494367/locations/global/workloadIdentityPools/github/providers/polars-bigquery-client
