name: Test Rust (Unit)

on:
  pull_request:
    paths:
      - crates/**
      - Cargo.toml
      - .github/workflows/test-rust-unit.yml
  push:
    branches:
      - main
    paths:
      - crates/**
      - Cargo.toml
      - .github/workflows/test-rust-unit.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Rust (Unit)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref_name == 'main' }}

      - name: Compile tests
        run: cargo test --workspace --exclude py-polars-bigquery --lib --bins --all-features --no-run

      - name: Run tests
        if: github.ref_name != 'main'
        run: >
          cargo test --workspace --exclude py-polars-bigquery --lib --bins --all-features
